# This workflow will do a clean install of node dependencies, build the source code and linter.
# Tis is used to make sure the code is clean and can be built successfully before merging to the main branch.

name: Node.js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack before setting up Node
        run: corepack enable
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Get yarn cache folder path
        id: yarn-cache-folder-path
        run: echo "YARN_CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_ENV

      - name: Cache Node.js modules
        id: yarn-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
